### ISSUE TITLE
Implement APK test framework

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/apk#1382]
**Description:**
$subject

**Tasks**

- [x] Add initial tests using cucumber framework https://github.com/wso2/apk/pull/1412
- [x] Improve the test framework to use TestNG https://github.com/wso2/apk/pull/1446
- [x] Update GitHub actions https://github.com/wso2/apk/pull/1443 https://github.com/wso2/apk/pull/1448 https://github.com/wso2/apk/pull/1452 https://github.com/wso2/apk/pull/1453 https://github.com/wso2/apk/pull/1451
