### ISSUE TITLE
Add required field to OAuth2

### ISSUE THREAD

**Issue by sgayangi** [wso2/apk#1941]
**Description**

- Similar to mTLS, OAuth2 needs to have a required field added that allows it to be mandatory or optional.
- Default required value for OAuth2 is mandatory.

**Tasks**
- [x] Add required field to AuthTypes in adapter
- [x] Add required field to AuthTypes in config-deployer-service
- [x] Update enforcer implementation to allow OAuth2 optional, mTLS optional
