### ISSUE TITLE
[Developer DS] Users should be able to subscribe to APIs using developer portal domain services call.

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/apk#305]
Users should be able to call /subscriptions and create subscriptions to APIs.

## Tasks

- [x] Create Subscription
- [x] Create Multiple Subscriptions
- [x] Delete Subscription
- [x] Retrieve Subscription by Id
- [x] Retrieve all subscriptions by App Id, API Id, both or none.
- [x] Update Subscription Policy of Subscription
- [x] Adding Unit Tests
